#docker-compose.yml is a required name for docker compose
version: '3'
services:
    tweets:
        build: tweepy/
        ports: # not really needed if nothing is penetraiting the docker
        - "5555:5555" # one port per system at a time
        volumes:
        - ./tweepy/:/app # make /web folder visible to the docker in /code

    mongodb:
        image: mongo # searches the web for the standard postgres db
        ports:
        - "27017:27017" # proxy number for local access : the actual port

    airflow:
        image: puckel/docker-airflow
        volumes:
        - ./ETL/src/:/usr/local/airflow/dags
        ports:
        - '8080:8080'

    sql:
        image: postgres
        ports:
        - "5432:5432"
        volumes:
        - ./SQL/:.

    flask:
        build: flask/
        ports: # not really needed if nothing is penetraiting the docker
        - "80:80" # one port per system at a time
        volumes:
        - ./flask/:/app # make /web folder visible to the docker in /code
