version: '3'
services:
  tweet_streamer:
    build: twitter_streamer/
    volumes:
    - ./twitter_streamer/src/:/src
    links:
    - mongodb

  mongodb:
    image: mongo
    ports:
    - '27017:27017'

  etl:
    build: etl/
    volumes:
    - ./etl/src/:/usr/local/airflow/dags
    restart: always
    depends_on:
        - postgres
    environment:
        - LOAD_EX=n
        - EXECUTOR=Local
    ports:
        - "8080:8080"
    command: webserver
    # healthcheck:
    #     test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
    #     interval: 30s
    #     timeout: 30s
    #     retries: 3

  postgres:
    build: postgres/
    ports:
    - '5430:5432'
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  # flask:
  #   build: flask/
  #   ports:
  #   - '80:80'
  #   volumes:
  #   - ./flask/src/:/src
  #   links:
  #   - mongodb

  # metabase:
  #   image: metabase/metabase
  #   ports:
  #   - '3000:3000'
